### ISSUE TITLE
Migration to cloud

### ISSUE THREAD

**Issue by rpasquini** [rpasquini/twitter_and_displacement#3]
- [ ] Define which cities's raw twiter data will be stored in the online server

_(I suggest we only upload the raw twitter data for the cities that we have not computed the counts yet.)  Emmanuel please create a new checklist for the cities we will process._  

- [x] Open aws account. Add credit card details. 
_Emmanuel, please open the AWS account that we will use._  

- [x] Create an aws instance and obtain security key

- [x] Define security group, and add permissions for the team.

- [x] Install mongodb in the server

_Lets do this three last steps together in a zoom session._

**Comment by Emman-Lopez-Oso** [comment]
@rpasquini, which of the AWS services do you use for your own computing for this project? I did not know there were over 12 different types of server products that they ran.

**Comment by rpasquini** [comment]
I am using a Linux server t2.medium and a EBS volume of 50 giga. I guess that should work for our requirements. But let's talk about it. 
My doubt is if we should use the aws server to store raw twitter data at this stage at all. In case of sharing only the counts (hex level) and counts data, all our requirements could fit in a much small server.

**Comment by Emman-Lopez-Oso** [comment]
@rpasquini , let me know what you think the ideal specifications are so that I can start the upload process sooner than later!

**Comment by rpasquini** [comment]
Hey @Emman-Lopez-Oso! I would say that we try with those I mentioned in my previous comment. Or is there anything else to define?

**Comment by Emman-Lopez-Oso** [comment]
@rpasquini, I guess not! It said let's talk about it, but is that in regards to what we outlined in the meeting last time? (I.e. Uploading raw twitter data vs hex-counts)??

**Comment by rpasquini** [comment]
Yes, you are right! Let's proceed putting that server up, and should allow us to process the raw data for the cities we haven't processed the counts yet. I guess this will be a trial and error process, but in any case I am confident we'll figure out how to tune the server in case we face a problem.

**Comment by Emman-Lopez-Oso** [comment]
@rpasquini The server instance is up and pending. I have added my own credentials and created key pairs for myself. Let me know when you're ready to define the security group and review the configurations. I think I made this one to very similar specifications as yours.
